//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhavyaModhiya_490_Model.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BhavyaModhiya_490Entities : DbContext
    {
        public BhavyaModhiya_490Entities()
            : base("name=BhavyaModhiya_490Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Seller> Seller { get; set; }
        public virtual DbSet<Bike> Bike { get; set; }
        public virtual DbSet<FAVORITES> FAVORITES { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<City> City { get; set; }
    }
}
