//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhavyaModhiya_490_Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        public int BikeID { get; set; }
        public int SellerID { get; set; }
        public string Brand { get; set; }
        public string Models { get; set; }
        public byte Years { get; set; }
        public int kilometresDriven { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
